## For more details on how to configure your build environment visit
# http://www.gradle.org/docs/current/userguide/build_environment.html

# Hemat RAM: Batasi penggunaan memori Java & Kotlin Daemon ke 512MB
org.gradle.jvmargs=-Xmx512M -Dkotlin.daemon.jvm.options\="-Xmx512M" -XX:+UseParallelGC

# AndroidX Settings
android.useAndroidX=true
android.enableJetifier=false
android.nonTransitiveRClass=false

# Optimasi Memori Rendah
# Wajib NONAKTIFKAN parallel dan daemon agar memori tidak bengkak
org.gradle.parallel=false
org.gradle.daemon=false
org.gradle.configureondemand=false
org.gradle.unsafe.configuration-cache=false

# Suppress deprecated warnings
android.suppressUnsupportedOptionWarnings=android.suppressUnsupportedOptionWarnings,android.nonFinalResIds

# Increase timeouts for JitPack downloads
systemProp.org.gradle.internal.http.connectionTimeout=180000
systemProp.org.gradle.internal.http.socketTimeout=180000

# Disable caching
org.gradle.caching=false
